# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('category_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField()),
                ('status_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_id', models.IntegerField()),
                ('sub_category_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Torrents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torrent_id', models.IntegerField()),
                ('torrent_name', models.TextField()),
                ('torrent_hash', models.TextField()),
                ('category_id', models.IntegerField()),
                ('sub_category_id', models.IntegerField()),
                ('status_id', models.IntegerField()),
            ],
        ),
    ]
